version: "3.9"

services:
  mp-inkasso:
    build: ./mp-inkasso
    container_name: mp-inkasso
    environment:
      PYTHONUNBUFFERED: true
    ports:
      - "1111:1111"
    networks:
      - net
    volumes:
      - ./mp-inkasso/data:/app/data
      - ./mp-inkasso/src:/app/src:ro
    env_file:
      - .env

  mp-postamt:
    build: ./mp-postamt
    container_name: mp-postamt
    ports:
      - "2222:2222"
    networks:
      - net
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=true
      - SMTP_RELAY_HOST=${SMTP_RELAY_HOST}
      - SMTP_RELAY_PORT=${SMTP_RELAY_PORT}
      - SMTP_RELAY_USERNAME=${SMTP_RELAY_USERNAME}
      - SMTP_RELAY_PASSWORD=${SMTP_RELAY_PASSWORD}

networks:
  net:
