version: "3.9"

services:
  mp-pegasos:
    build: ./mp-pegasos
    container_name: mp-pegasos
    environment:
      PYTHONUNBUFFERED: true
    ports:
      - "5000:5000"
    networks:
      - net
#    network_mode: host # expose whole container to host networkip addr show
    volumes:
      - ./mp-pegasos/data:/app/data
      - ./mp-pegasos/src:/app/src:ro
#      - ./mp-pegasos/makefile:/app/makefile:ro

  mp-hermes:
    container_name: mp-hermes
    build: ./mp-hermes
    depends_on:
      - mp-pegasos
    ports:
      - "8080:8080"
    networks:
      - net

networks:
  net: