services:
    mp-inkasso:
#        container_name: inkasso-dev
        restart: no
        environment:
            ENVIRONMENT: development
        ports:
            - "1111:1111"
        volumes:
            - ./mp-inkasso/data:/app/data
            - ./mp-inkasso/src:/app/src:ro
        deploy:
            resources:
                limits:
                    cpus: "7.0"
                    memory: 30gb

#    mp-postamt:
##        container_name: postamt-dev
#        restart: no
#        environment:
#            ENVIRONMENT: development
#        deploy:
#            resources:
#                limits:
#                    cpus: "1.0"
#                    memory: 600m

    mp-silo:
#        container_name: silo-dev
        volumes:
            - ./mp-silo/data:/var/lib/postgresql/data
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 600m

    mp-depot:
#        container_name: depot-dev
        restart: no
        ports:
            - "5555:5555"
        environment:
            NODE_ENV: development
        deploy:
            resources:
                limits:
                    cpus: "7.0"
                    memory: 30g
        volumes:
            - ./mp-depot/config:/opt/app/config:ro
            - ./mp-depot/src:/opt/app/src:rw
            - ./mp-depot/types:/opt/app/types:rw
            - ./mp-depot/package.json:/opt/package.json:ro
            - ./mp-depot/database:/opt/app/database
            - ./mp-depot/public/uploads:/opt/app/public/uploads

#    mp-shop-api:
##        container_name: shop-api-dev
#        restart: no
#        environment:
#            NODE_ENV: development
#        volumes:
#            - ./mp-shop-api/src:/app/src:ro

    mp-shop:
#        container_name: shop-dev
        build:
            context: ./mp-shop
            target: development
        restart: no
        deploy:
            resources:
                limits:
                    cpus: "2.0"
                    memory: 2gb
        volumes:
            - ./mp-shop/src:/app/src:ro
            - ./mp-shop/package.json:/app/package.json:ro
            - ./mp-shop/vite.config.ts:/app/vite.config.ts:ro

    mp-proxy:
#        container_name: proxy-dev
        build: ./mp-proxy
        restart: no
        environment:
            NGINX_DEBUG: true
        depends_on:
            certs:
                condition: service_completed_successfully
        volumes:
            - ./mp-proxy/nginx-template.conf:/nginx-template.conf:ro
            - ./mp-proxy/logs/:/var/log/nginx/:rw
            - cache-data:/cache
            - certs-data:/etc/nginx/certs:ro
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 600m

    certs:
#        container_name: certs-dev
        image: !reset null
        command: !reset null
        build: ./certs
        environment:
            HOST: ${CERTS_DOMAIN:-localhost}
            EMAIL: ${CERTS_EMAIL:-admin@localhost}
        volumes:
            - certs-data:/etc/ssl

    prometheus:
#        container_name: prometheus-dev
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 600m
#    grafana:
##        container_name: grafana-dev
#
#    umami:
##        container_name: umami-dev
#        restart: no
#
#    umami-db:
##        container_name: umami-db-dev
#        restart: no
