version: "3.9"

services:
  mp-inkasso:
    build: ./mp-inkasso
    container_name: mp-inkasso
#    restart: unless-stopped
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: true
    ports:
      - "1111:1111"
    networks:
      - net
    volumes:
      - ./mp-inkasso/data:/app/data
      - ./mp-inkasso/src:/app/src:ro

  mp-postamt:
    build: ./mp-postamt
    container_name: mp-postamt
#    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=true
      - SMTP_RELAY_HOST=${SMTP_RELAY_HOST}
      - SMTP_RELAY_PORT=${SMTP_RELAY_PORT}
      - SMTP_RELAY_USERNAME=${SMTP_RELAY_USERNAME}
      - SMTP_RELAY_PASSWORD=${SMTP_RELAY_PASSWORD}
    ports:
      - "2222:2222"
    networks:
      - net

  mp-depot:
    container_name: mp-depot
    build: ./mp-depot
    image: strapi:latest
#    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: mp-silo
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: false
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
#      NODE_ENV: ${NODE_ENV}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      PORT: 5555
    volumes:
      - ./mp-depot/config:/opt/app/config
      - ./mp-depot/src:/opt/app/src
      - ./mp-depot/package.json:/opt/package.json
#      - ./mp-depot/yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./mp-depot/public/uploads:/opt/app/public/uploads
    ports:
      - "5555:5555"
    networks:
      - net
      - data
    depends_on:
      - mp-silo

  mp-silo:
    container_name: mp-silo
#    restart: unless-stopped
    image: postgres:alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
#      - silo-data:/var/lib/postgresql/data/ #using a volume
      - ./mp-silo/data:/var/lib/postgresql/data/ # if you want to use a bind folder
#      - ./mp-silo/seed/backup_2023-03-10_23-44-50.sql:/docker-entrypoint-initdb.d/seed_database.sql
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - data

  mp-konsole:
    container_name: mp-konsole
    build: ./mp-konsole
    depends_on:
      - mp-inkasso
      - mp-depot
    ports:
      - "3333:3333"
    networks:
      - net
    volumes:
      - ./mp-konsole/src:/app/src:ro

#volumes:
#  silo-data:


networks:
  net:
  data:
